# Generated by Django 3.2.4 on 2021-06-24 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lenguages', '0002_auto_20210623_2028'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SaleDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sale', models.ManyToManyField(to='lenguages.Sale')),
            ],
        ),
    ]
